# Generated by Django 5.2.6 on 2025-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destry', '0004_alter_cartitem_cart_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
